name: generate-site
run-name: ${{ github.actor }} is generating the site
on: [push]
jobs:
  generate-site:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-python@v7
        with:
          python-version: '3.12'
      - run: pip install -r requirements.txt
      - run: python3 site_generator.py
      - uses: actions/upload-artifact@v7
        with:
          name: generated-site
          path: out
