name: publish-site
run-name: ${{ github.actor }} is publishing the site to GitHub Pages
on:
  workflow_run:
    workflows: ["generate-site"]
    branches: [main]
    types:
      - completed
jobs:
  publish-site:
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - uses: actions/deploy-pages@v5
        with:
          artifact_name: generated-site
